# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cuda_version: "13.0.0"
fabric_manager_version: "580.65.06"

_pkg_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"
_cuda_suffix: "{{ '' if ansible_architecture == 'x86_64' else '_sbsa' }}"

cuda_installer_file_name: "cuda_{{cuda_version}}_{{fabric_manager_version}}_linux{{ _cuda_suffix }}.run"
cuda_runfile_url: "https://developer.download.nvidia.com/compute/cuda/{{ cuda_version }}/local_installers/{{ cuda_installer_file_name }}"
nvidia_container_toolkit_version: "1.19.0-1"
nvidia_driver_package_version: "580-server"
fabricmanager_deb: "nvidia-fabricmanager_{{fabric_manager_version}}-1_{{ _pkg_arch }}.deb"
doca_version: "3.2.1"
doca_repo_url: "https://linux.mellanox.com/public/repo/doca/{{ doca_version }}/{{ ansible_distribution | lower }}{{ (ansible_distribution_version.split('.'))[0:2] | join('.') }}/{{ ansible_architecture }}"