# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Add Google Cloud apt-key.gpg for repository verification
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /etc/apt/trusted.gpg.d/cloud.google.gpg
    state: present
  register: add_google_key

- name: Wait for APT Lock
  ansible.builtin.shell: |
    while fuser /var/lib/dpkg/lock >/dev/null 2>&1 || \
          fuser /var/lib/apt/lists/lock >/dev/null 2>&1 || \
          fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
      sleep 5
    done
  changed_when: false

- name: Add gpudirect-gib-apt repository to sources.list.d
  ansible.builtin.apt_repository:
    repo: 'deb https://packages.cloud.google.com/apt gpudirect-gib-apt main'
    filename: nccl-gib
    state: present
  register: add_nccl_repo

- name: "Install NCCL stack: nccl-gib, libnccl2, and libnccl-dev"
  # Along with nccl-gib plugin, we also install libnccl2 and libnccl-dev
  # to complete the NCCL stack with validated versions.
  # Using wildcards for libnccl and libnccl-dev since they are tagged with `+cudaXX.Y`
  ansible.builtin.apt:
    name:
      - "nccl-gib={{nccl_gib_version}}"
      - "libnccl2={{nccl_version}}*"
      - "libnccl-dev={{nccl_version}}*"
    state: present
    update_cache: yes

- name: Freeze NCCL stack packages
  # We hold the versions of the entire NCCL stack to ensure compatibility
  # and prevent accidental updates during image upgrades.
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - "nccl-gib"
    - "libnccl2"
    - "libnccl-dev"
