# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Execute conditionally gated tasks natively
  block:
    - name: Include OS Family Dependent Vars
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_facts['distribution']|lower }}-{{ ansible_facts['distribution_version'] }}.yml"
        - "{{ ansible_facts['distribution']|lower }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['distribution']|lower }}.yml"

    - name: Ensure installation directory exists for NVIDIA Stack
      ansible.builtin.file:
        path: "{{ nvidia_installation_path }}"
        state: directory
        mode: "0755"
      become: true

    - name: Include OS Family Dependent Tasks for NVIDIA Stack
      include_tasks: "{{ item }}"
      with_first_found:
        - os/{{ ansible_facts['distribution']|lower }}-{{ ansible_facts['distribution_version'] }}.yml
        - os/{{ ansible_facts['distribution']|lower }}-{{ ansible_facts['distribution_major_version'] }}.yml
        - os/{{ ansible_facts['distribution']|lower }}.yml

    - name: Export global CUDA binary and header paths
      ansible.builtin.copy:
        dest: /etc/profile.d/cuda_path.sh
        mode: "0644"
        content: |
          export PATH=$PATH:/usr/local/cuda/bin
          export CPATH=$CPATH:/usr/local/cuda/include
      become: true
  when: install_nvidia_stack | default(false) | bool
