# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
rdma_libfabric_version: "2.2.0"

ciq_rdma_packages:
  - kmod-idpf-irdma
  - rdma-core
  - rdma-core-devel
  - libibverbs
  - libibverbs-utils
  - librdmacm
  - librdmacm-utils
  - libibumad
  - infiniband-diags

rdma_build_dependencies:
  - git
  - autoconf
  - automake
  - libtool
  - bzip2
  - pciutils
  - pciutils-devel
  - gcc
  - make
  - rpm-build

rdma_versionlock_packages:
  - kmod-idpf-irdma
  - rdma-core
  - rdma-core-devel
  - libibverbs
  - libibverbs-utils
  - librdmacm
  - librdmacm-utils
  - libibumad
  - infiniband-diags
  - libfabric
  - perftest
