# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# Tasks for preparing the OS, including installing base packages and RDMA drivers.

- name: Configure Console (Before Reboot)
  block:
    - name: Edit serial-getty service for ttyS1 (Autologin Root)
      ansible.builtin.replace:
        path: /lib/systemd/system/serial-getty@.service
        regexp: 'ExecStart=-/sbin/agetty .*'
        replace: 'ExecStart=-/sbin/agetty -n --autologin root --keep-baud 115200,38400,9600 %I $TERM'

    - name: Enable ttyS1 console
      ansible.builtin.systemd:
        name: serial-getty@ttyS1.service
        enabled: yes

    - name: Disable ttyS0 console
      ansible.builtin.systemd:
        name: serial-getty@ttyS0.service
        enabled: no

    - name: Suppress kernel messages in .bashrc
      ansible.builtin.blockinfile:
        path: /root/.bashrc
        block: |
          # Suppress kernel messages on the root logins.
          dmesg -D

- name: Setup Repositories
  block:
    - name: Add Parallelstore Repo
      ansible.builtin.yum_repository:
        name: "parallelstore-v2-6-el{{ ansible_distribution_major_version }}"
        description: "Parallelstore EL{{ ansible_distribution_major_version }} v2.6"
        baseurl: "{{ parallelstore_repo_url }}"
        enabled: yes
        repo_gpgcheck: no
        gpgcheck: no

    - name: Add Intel HPC Platform Repo
      ansible.builtin.yum_repository:
        name: intel-hpc-platform
        description: Intel(R) HPC Platform meta-Packages
        baseurl: "{{ intel_repo_url }}"
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: no
        gpgkey: https://yum.repos.intel.com/hpc-platform/el7/setup/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
      when: enable_intel_compliance

- name: Disable Auto-Updates (yum-cron)
  ansible.builtin.lineinfile:
    path: "{{ cron_conf_file }}"
    line: "exclude = google-hpc-*"
    insertafter: '^\s*exclude'
  loop:
    - /etc/yum/yum-cron-hourly.conf
    - /etc/yum/yum-cron.conf
  loop_control:
    loop_var: cron_conf_file
  failed_when: false

- name: Check for man-db-cache-update.service
  ansible.builtin.stat:
    path: /lib/systemd/system/man-db-cache-update.service
  register: man_db_service_stat

- name: Force stop, disable, and mask man-db-cache-update.service
  ansible.builtin.systemd:
    name: man-db-cache-update.service
    enabled: no
    masked: yes
    state: stopped
    daemon_reload: yes
  when: man_db_service_stat.stat.exists

- name: Install Base Dependencies
  block:
    - name: Remove conflicting pre-installed RDMA packages
      ansible.builtin.dnf:
        name:
          - perftest
          - infiniband-diags
          - rdma-core-devel
        state: absent
      become: true

    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install EPEL Release
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: Enable PowerTools Repository (Rocky-Linux-8)
      ansible.builtin.command: dnf config-manager --set-enabled powertools
      when: ansible_distribution_major_version == '8'
      changed_when: false
      register: powertools_result
      failed_when: "powertools_result.rc != 0 and 'No matches found for argument' not in powertools_result.stderr"

    - name: Enable CRB Repository (Rocky-Linux-9)
      ansible.builtin.command: dnf config-manager --set-enabled crb
      when: ansible_distribution_major_version == '9'
      changed_when: false
      register: crb_result
      failed_when: "crb_result.rc != 0 and 'No matches found for argument' not in crb_result.stderr"

- name: Install Standard EL RPMs
  block:
    - name: Clean DNF Cache
      ansible.builtin.command: dnf clean all
      changed_when: false

    - name: Install EL Packages
      ansible.builtin.dnf:
        name: "{{ vars['el' + ansible_distribution_major_version + '_rpm_list'] }}"
        state: present
        update_cache: yes
      retries: 5
      delay: 10
      register: dnf_result
      until: dnf_result is success

    - name: Install EL Groups
      ansible.builtin.dnf:
        name: "@{{ group_item }}"
        state: present
      loop: "{{ vars['el' + ansible_distribution_major_version + '_group_list'] }}"
      loop_control:
        loop_var: group_item

- name: Install RDMA Drivers
  block:
    - name: Configure ib_core options
      ansible.builtin.copy:
        dest: /etc/modprobe.d/ib_core.conf
        content: "options ib_core send_queue_size=8192 recv_queue_size=8192\n"

    - name: Configure rdma_ucm udev rule
      ansible.builtin.copy:
        dest: /usr/lib/udev/rules.d/99-rdma_ucm.rules
        content: 'SUBSYSTEM=="module", KERNEL=="rdma_ucm", ACTION=="add", RUN+="/bin/bash -c ''/usr/sbin/sysctl -w net.rdma_ucm.max_backlog=32768''"'

    - name: Reload udev rules
      ansible.builtin.command: udevadm control --reload-rules

    - name: Install RDMA packages
      ansible.builtin.dnf:
        name: "{{ rdma_pkg_list }}"
        state: present