# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Read package list from file
  set_fact:
    package_lines: "{{ lookup('file', output_file).splitlines() }}"

- name: Parse package names
  set_fact:
    packages_to_check: "{{ package_lines[1:] | map('regex_replace', '^([^=]+)=.*$', '\\1') | map('replace', '\"', '') | list }}"

- name: Normalize package names for Ubuntu 24.04
  set_fact:
    # Replaces 'openssl' with 'libssl3t64' only if on Ubuntu 24.04
    packages_to_check: "{{ packages_to_check | map('regex_replace', '^openssl$', 'libssl3t64') | list }}"
  when:
    - ansible_distribution_version == "24.04"

- name: Ensure target license directory exists
  file:
    path: "{{ license_dir }}"
    state: directory
    mode: '0755'

- name: Check for existence of copyright files
  stat:
    path: "/usr/share/doc/{{ item }}/copyright"
  register: copyright_stats
  loop: "{{ packages_to_check }}"

- name: Copy licenses to central directory
  copy:
    src: "/usr/share/doc/{{ item.item }}/copyright"
    dest: "{{ license_dir }}/{{ item.item }}"
    remote_src: yes
    mode: '0644'
  when: item.stat.exists
  loop: "{{ copyright_stats.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Collect specialized licenses from custom paths
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/usr/share/third_party/licenses/{{ item.name }}"
    remote_src: yes
    mode: '0644'
  loop:
    - name: "cuda-toolkit-and-driver"
      src: "/usr/local/cuda/EULA.txt"

    - name: "libnvfatbin"
      src: "/usr/local/cuda/EULA.txt"

    - name: "slurm-gcp"
      src: "/opt/slurm-gcp-repo/LICENSE"

    - name: "docker-containerd"
      src: "/usr/share/doc/containerd.io/copyright"

    - name: "nvidia-fabricmanager"
      src: "/usr/share/doc/nvidia-fabricmanager-{{ fabric_manager_version.split('.')[0] }}/copyright"

    - name: "spack"
      src: "/opt/apps/spack/LICENSE-MIT"
  ignore_errors: yes  # Useful if a specific version isn't installed on a specific node
  loop_control:
    label: "{{ item.name }}"

- name: Download specialized licenses from web URLs
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/usr/share/third_party/licenses/{{ item.name }}"
    mode: '0644'
  loop:
    - name: "lmod"
      url: "https://raw.githubusercontent.com/TACC/Lmod/main/License"

    - name: "openmpi"
      url: "https://raw.githubusercontent.com/open-mpi/ompi/main/LICENSE"
  become: yes
  ignore_errors: yes
  loop_control:
    label: "Downloading {{ item.name }} license"

- name: Download specialized licenses for slurm related packages from web URLs
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/usr/share/third_party/licenses/{{ item.name }}"
    mode: '0644'
  loop:
    - name: "pyxis"
      url: "https://raw.githubusercontent.com/NVIDIA/pyxis/main/LICENSE"
  become: yes
  ignore_errors: yes
  when:
    - install_slurm
  loop_control:
    label: "Downloading {{ item.name }} license"

- name: Download specialized licenses for GPU specific packages from web URLs
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/usr/share/third_party/licenses/{{ item.name }}"
    mode: '0644'
  loop:
    - name: "nccl"
      url: "https://raw.githubusercontent.com/NVIDIA/nccl/master/LICENSE.txt"
  become: yes
  ignore_errors: yes
  when:
    - hw_type == "gpu"
  loop_control:
    label: "Downloading {{ item.name }} license"